-- Baseline migration: full schema as of 2026-03-29 (migrations 001-011 applied).
-- Generated manually from db/schema.sql + db/migrations/ + db/rls-policies.sql
-- because supabase db pull returned an empty file (connection issue).
--
-- This file represents the authoritative current schema for Supabase CLI.
-- Future schema changes must use: supabase migration new <name>
-- Do not edit this file after the initial commit.

-- ============================================================
-- Extensions
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- Core tables
-- ============================================================

-- One row per earnings call
CREATE TABLE IF NOT EXISTS calls (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticker          TEXT NOT NULL,
    company_name    TEXT,
    industry        TEXT,
    fiscal_quarter  TEXT,
    call_date       DATE,
    transcript_json TEXT,
    transcript_text TEXT NOT NULL,
    token_count     INTEGER,
    prepared_len    INTEGER,
    qa_len          INTEGER,
    created_at      TIMESTAMPTZ DEFAULT now(),
    UNIQUE (ticker, fiscal_quarter)
);

-- Unique speakers per call, with enriched metadata
CREATE TABLE IF NOT EXISTS speakers (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id     UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    role        TEXT NOT NULL,
    title       TEXT,
    firm        TEXT,
    turn_count  INTEGER NOT NULL,
    UNIQUE (call_id, name)
);

-- Atomic text units (turns, sentences)
CREATE TABLE IF NOT EXISTS spans (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id         UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    speaker_id      UUID REFERENCES speakers(id),
    section         TEXT NOT NULL,
    span_type       TEXT NOT NULL,
    sequence_order  INTEGER NOT NULL,
    text            TEXT NOT NULL,
    char_count      INTEGER NOT NULL,
    textrank_score  NUMERIC,
    embedding       vector(1024),
    CONSTRAINT valid_section CHECK (section IN ('prepared', 'qa')),
    CONSTRAINT valid_span_type CHECK (span_type IN ('turn', 'sentence'))
);

CREATE INDEX IF NOT EXISTS idx_spans_call      ON spans(call_id);
CREATE INDEX IF NOT EXISTS idx_spans_speaker   ON spans(speaker_id);
CREATE INDEX IF NOT EXISTS idx_spans_section   ON spans(call_id, section);
CREATE INDEX IF NOT EXISTS idx_spans_embedding ON spans USING hnsw (embedding vector_cosine_ops);

-- ============================================================
-- Extracted analysis tables
-- ============================================================

-- NMF themes per call (topic_name added in migration 008)
CREATE TABLE IF NOT EXISTS call_topics (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id     UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    label       INTEGER NOT NULL,
    terms       TEXT[] NOT NULL,
    weight      NUMERIC NOT NULL,
    rank_order  INTEGER NOT NULL,
    topic_name  TEXT DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_topics_call ON call_topics(call_id);

-- TF-IDF keyword associations (call-level)
CREATE TABLE IF NOT EXISTS span_keywords (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id    UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    term       TEXT NOT NULL,
    score      NUMERIC NOT NULL,
    ngram_size INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_keywords_call ON span_keywords(call_id);
CREATE INDEX IF NOT EXISTS idx_keywords_term ON span_keywords(term);

-- ============================================================
-- Q&A structure
-- ============================================================

CREATE TABLE IF NOT EXISTS qa_pairs (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id          UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    exchange_order   INTEGER NOT NULL,
    question_span_id UUID NOT NULL REFERENCES spans(id),
    answer_span_id   UUID NOT NULL REFERENCES spans(id),
    UNIQUE (question_span_id, answer_span_id)
);

CREATE INDEX IF NOT EXISTS idx_qa_call ON qa_pairs(call_id);

-- ============================================================
-- Learning tool tables
-- ============================================================

-- User study sessions (user_id added as nullable in migration 009)
CREATE TABLE IF NOT EXISTS learning_sessions (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID,
    call_id      UUID NOT NULL REFERENCES calls(id),
    started_at   TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ,
    notes        TEXT
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON learning_sessions(user_id);

-- Feynman explanation exercises
CREATE TABLE IF NOT EXISTS concept_exercises (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id          UUID NOT NULL REFERENCES learning_sessions(id) ON DELETE CASCADE,
    concept_label       TEXT NOT NULL,
    user_explanation    TEXT,
    ai_critique         TEXT,
    revised_explanation TEXT,
    confidence          TEXT CHECK (confidence IN ('low', 'medium', 'high'))
);

-- Per-step completion tracking (added in migration 007)
CREATE TABLE IF NOT EXISTS transcript_progress (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id     UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    step_number INTEGER NOT NULL CHECK (step_number BETWEEN 1 AND 6),
    viewed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (call_id, step_number)
);

CREATE INDEX IF NOT EXISTS idx_transcript_progress_call ON transcript_progress(call_id);

-- ============================================================
-- Agentic Pipeline Outputs
-- ============================================================

CREATE TABLE IF NOT EXISTS transcript_chunks (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id             UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    chunk_id            TEXT NOT NULL,
    chunk_type          TEXT NOT NULL,
    sequence_order      INTEGER NOT NULL,
    tier1_score         INTEGER,
    needs_deep_analysis BOOLEAN DEFAULT FALSE,
    chunk_text          TEXT
);

-- explanation column added in migration 001
CREATE TABLE IF NOT EXISTS extracted_terms (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id     UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    chunk_id    TEXT NOT NULL,
    term        TEXT NOT NULL,
    definition  TEXT NOT NULL,
    explanation TEXT DEFAULT '',
    category    TEXT NOT NULL DEFAULT 'industry'
);

CREATE TABLE IF NOT EXISTS core_concepts (
    id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id  UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    chunk_id TEXT NOT NULL,
    concept  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS extracted_takeaways (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id        UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    chunk_id       TEXT NOT NULL,
    takeaway       TEXT NOT NULL,
    why_it_matters TEXT NOT NULL
);

-- analyst_name/question_topic/question_text/answer_text added in migration 004
CREATE TABLE IF NOT EXISTS evasion_analysis (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id             UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    chunk_id            TEXT NOT NULL,
    analyst_name        TEXT,
    question_topic      TEXT,
    question_text       TEXT,
    answer_text         TEXT,
    analyst_concern     TEXT NOT NULL,
    defensiveness_score INTEGER NOT NULL,
    evasion_explanation TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS misconceptions (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id           UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    chunk_id          TEXT NOT NULL,
    fact              TEXT NOT NULL,
    misinterpretation TEXT NOT NULL,
    correction        TEXT NOT NULL
);

-- strategic_shifts is JSONB[] after migration 006; call_summary added in migration 005
CREATE TABLE IF NOT EXISTS call_synthesis (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id            UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE UNIQUE,
    overall_sentiment  TEXT NOT NULL,
    executive_tone     TEXT NOT NULL,
    key_themes         TEXT[] NOT NULL,
    strategic_shifts   JSONB[] DEFAULT '{}',
    analyst_sentiment  TEXT NOT NULL,
    call_summary       TEXT
);

CREATE TABLE IF NOT EXISTS competitors (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id                 UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    competitor_name         TEXT NOT NULL,
    competitor_ticker       TEXT,
    description             TEXT,
    mentioned_in_transcript BOOLEAN NOT NULL DEFAULT FALSE,
    fetched_at              TIMESTAMPTZ DEFAULT now(),
    UNIQUE (call_id, competitor_name)
);

CREATE INDEX IF NOT EXISTS idx_competitors_call ON competitors(call_id);

-- Observability events (added in migration 011)
CREATE TABLE IF NOT EXISTS analytics_events (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name TEXT NOT NULL,
    session_id UUID,
    properties JSONB,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_analytics_event_name ON analytics_events(event_name);
CREATE INDEX IF NOT EXISTS idx_analytics_created_at  ON analytics_events(created_at);

-- ============================================================
-- User Roles (added in migration 010)
-- ============================================================

CREATE TYPE public.user_role AS ENUM ('admin', 'learner');

CREATE TABLE IF NOT EXISTS public.profiles (
    id   UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role public.user_role NOT NULL DEFAULT 'learner'
);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, role) VALUES (NEW.id, 'learner');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- Row Level Security
-- ============================================================

-- learning_sessions: users can only read/write/update their own rows
ALTER TABLE public.learning_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_read_own_sessions"
    ON public.learning_sessions
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "users_insert_own_sessions"
    ON public.learning_sessions
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users_update_own_sessions"
    ON public.learning_sessions
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- analytics_events: RLS enabled with no policies (service-role only)
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- profiles: users can read their own profile row
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_read_own_profile"
    ON public.profiles
    FOR SELECT
    USING (auth.uid() = id);
